include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ArizonaPrefs

ArizonaPrefs_FILES = ARIRootListController.xm POGSwitchWithInfoCell.m
ArizonaPrefs_FRAMEWORKS = UIKit
ArizonaPrefs_PRIVATE_FRAMEWORKS = Preferences
ArizonaPrefs_INSTALL_PATH = /Library/PreferenceBundles
ArizonaPrefs_CFLAGS = -fobjc-arc -Wdeprecated-declarations -Wno-deprecated-declarations

include $(THEOS_MAKE_PATH)/bundle.mk